### ISSUE TITLE
collection-repreat breaks android scrolling

### ISSUE THREAD

**Issue by CamMakoJ** [CamMakoJ/acimsApp#14]

**Comment by ajolson8** [comment]
[search.zip](https://github.com/CamMakoJ/acimsApp/files/1216505/search.zip)
replace your search.html with this.

**Comment by ajolson8** [comment]
also have to add 
`ng-if="!moredata" `
into the infinite-scroll otherwise it seems to create extra entries at the end.

**Comment by CamMakoJ** [comment]
fixed
